In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(1)

In [7]:
lstm = nn.LSTM(3,3)
# Input of the dimension 1 x 3 x 7
inputs = [torch.rand(1,3) for _ in range(7)]
hidden = (torch.randn(1,1,3),torch.randn(1,1,3)) 
output, hidden_2 = lstm(inputs, hidden)
for i in inputs:
    out, hidden = lstm(i.view(1,1,-1), hidden)
    


AttributeError: 'list' object has no attribute 'size'

In [6]:
print("INPUTS \n")
print(inputs,"\n")

print("HIDDEN \n")
print(hidden,"\n")


print("LSTM Parameters IH \n")
print(lstm.weight_ih_l0,"\n")

print("LSTM Parameters HH \n")
print(lstm.weight_hh_l0, "\n")
print("HIDDEN \n")
print(hidden,"\n")
print("OUTPUT \n")
print(out)

INPUTS 

[tensor([[0.6705, 0.5896, 0.2873]]), tensor([[0.3486, 0.9579, 0.4075]]), tensor([[0.7819, 0.7165, 0.1768]]), tensor([[0.0748, 0.9799, 0.5261]]), tensor([[0.8427, 0.6036, 0.6608]]), tensor([[0.8735, 0.9741, 0.1682]]), tensor([[0.5625, 0.8731, 0.8622]])] 

HIDDEN 

(tensor([[[-0.0919, -0.2792, -0.0700]]], grad_fn=<StackBackward>), tensor([[[-0.2116, -0.4703, -0.3821]]], grad_fn=<StackBackward>)) 

LSTM Parameters IH 

Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119],
        [ 0.2710, -0.5435,  0.3462],
        [-0.1188,  0.2937,  0.0803],
        [-0.0707,  0.1601,  0.0285],
        [ 0.2109, -0.2250, -0.0421],
        [-0.0520,  0.0837, -0.0023],
        [ 0.5047,  0.1797, -0.2150],
        [-0.3487, -0.0968, -0.2490],
        [-0.1850,  0.0276,  0.3442],
        [ 0.3138, -0.5644,  0.3579],
        [ 0.1613,  0.5476,  0.3811],
        [-0.5260, -0.5489, -0.2785]], requires_grad=True) 

LSTM Parameters HH 

Parameter containing:
tensor([[ 0.5070, -0.0962,  0.2471],
  